# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: circuit_computation_request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="circuit_computation_request.proto",
    package="",
    syntax="proto3",
    serialized_options=b"\252\002\010Protobuf",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n!circuit_computation_request.proto"W\n\x19\x43ircuitComputationRequest\x12\x12\n\ncircuit_id\x18\x01 \x01(\t\x12\x0e\n\x06qubits\x18\x02 \x03(\x05\x12\x16\n\x0etime_block_ids\x18\x03 \x03(\tB\x0b\xaa\x02\x08Protobufb\x06proto3',
)


_CIRCUITCOMPUTATIONREQUEST = _descriptor.Descriptor(
    name="CircuitComputationRequest",
    full_name="CircuitComputationRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="circuit_id",
            full_name="CircuitComputationRequest.circuit_id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="qubits",
            full_name="CircuitComputationRequest.qubits",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="time_block_ids",
            full_name="CircuitComputationRequest.time_block_ids",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=37,
    serialized_end=124,
)

DESCRIPTOR.message_types_by_name[
    "CircuitComputationRequest"
] = _CIRCUITCOMPUTATIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CircuitComputationRequest = _reflection.GeneratedProtocolMessageType(
    "CircuitComputationRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _CIRCUITCOMPUTATIONREQUEST,
        "__module__": "circuit_computation_request_pb2"
        # @@protoc_insertion_point(class_scope:CircuitComputationRequest)
    },
)
_sym_db.RegisterMessage(CircuitComputationRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
