# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: error.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.param_string_pb2 as param__string__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="error.proto",
    package="",
    syntax="proto3",
    serialized_options=b"\252\002\010Protobuf",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0b\x65rror.proto\x1a\x12param_string.proto"\x8e\x01\n\nErrorModel\x12\x35\n\x15\x64iscrete_error_params\x18\x01 \x01(\x0b\x32\x14.DiscreteErrorParamsH\x00\x12\x39\n\x17\x63ontinuous_error_params\x18\x02 \x01(\x0b\x32\x16.ContinuousErrorParamsH\x00\x42\x0e\n\x0c\x65rror_params"\\\n\x13\x44iscreteErrorParams\x12\'\n\x11xyz_probabilities\x18\x01 \x01(\x0b\x32\x0c.InputValue3\x12\x1c\n\x07scaling\x18\x02 \x01(\x0b\x32\x0b.InputValue"\x9e\x01\n\x15\x43ontinuousErrorParams\x12\x1e\n\x08xyz_axes\x18\x01 \x01(\x0b\x32\x0c.InputValue3\x12"\n\rrotation_mean\x18\x02 \x01(\x0b\x32\x0b.InputValue\x12#\n\x0erotation_stdev\x18\x03 \x01(\x0b\x32\x0b.InputValue\x12\x1c\n\x07scaling\x18\x04 \x01(\x0b\x32\x0b.InputValueB\x0b\xaa\x02\x08Protobufb\x06proto3',
    dependencies=[
        param__string__pb2.DESCRIPTOR,
    ],
)


_ERRORMODEL = _descriptor.Descriptor(
    name="ErrorModel",
    full_name="ErrorModel",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="discrete_error_params",
            full_name="ErrorModel.discrete_error_params",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="continuous_error_params",
            full_name="ErrorModel.continuous_error_params",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="error_params",
            full_name="ErrorModel.error_params",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=36,
    serialized_end=178,
)


_DISCRETEERRORPARAMS = _descriptor.Descriptor(
    name="DiscreteErrorParams",
    full_name="DiscreteErrorParams",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="xyz_probabilities",
            full_name="DiscreteErrorParams.xyz_probabilities",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="scaling",
            full_name="DiscreteErrorParams.scaling",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=180,
    serialized_end=272,
)


_CONTINUOUSERRORPARAMS = _descriptor.Descriptor(
    name="ContinuousErrorParams",
    full_name="ContinuousErrorParams",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="xyz_axes",
            full_name="ContinuousErrorParams.xyz_axes",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="rotation_mean",
            full_name="ContinuousErrorParams.rotation_mean",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="rotation_stdev",
            full_name="ContinuousErrorParams.rotation_stdev",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="scaling",
            full_name="ContinuousErrorParams.scaling",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=275,
    serialized_end=433,
)

_ERRORMODEL.fields_by_name["discrete_error_params"].message_type = _DISCRETEERRORPARAMS
_ERRORMODEL.fields_by_name[
    "continuous_error_params"
].message_type = _CONTINUOUSERRORPARAMS
_ERRORMODEL.oneofs_by_name["error_params"].fields.append(
    _ERRORMODEL.fields_by_name["discrete_error_params"]
)
_ERRORMODEL.fields_by_name[
    "discrete_error_params"
].containing_oneof = _ERRORMODEL.oneofs_by_name["error_params"]
_ERRORMODEL.oneofs_by_name["error_params"].fields.append(
    _ERRORMODEL.fields_by_name["continuous_error_params"]
)
_ERRORMODEL.fields_by_name[
    "continuous_error_params"
].containing_oneof = _ERRORMODEL.oneofs_by_name["error_params"]
_DISCRETEERRORPARAMS.fields_by_name[
    "xyz_probabilities"
].message_type = param__string__pb2._INPUTVALUE3
_DISCRETEERRORPARAMS.fields_by_name[
    "scaling"
].message_type = param__string__pb2._INPUTVALUE
_CONTINUOUSERRORPARAMS.fields_by_name[
    "xyz_axes"
].message_type = param__string__pb2._INPUTVALUE3
_CONTINUOUSERRORPARAMS.fields_by_name[
    "rotation_mean"
].message_type = param__string__pb2._INPUTVALUE
_CONTINUOUSERRORPARAMS.fields_by_name[
    "rotation_stdev"
].message_type = param__string__pb2._INPUTVALUE
_CONTINUOUSERRORPARAMS.fields_by_name[
    "scaling"
].message_type = param__string__pb2._INPUTVALUE
DESCRIPTOR.message_types_by_name["ErrorModel"] = _ERRORMODEL
DESCRIPTOR.message_types_by_name["DiscreteErrorParams"] = _DISCRETEERRORPARAMS
DESCRIPTOR.message_types_by_name["ContinuousErrorParams"] = _CONTINUOUSERRORPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ErrorModel = _reflection.GeneratedProtocolMessageType(
    "ErrorModel",
    (_message.Message,),
    {
        "DESCRIPTOR": _ERRORMODEL,
        "__module__": "error_pb2"
        # @@protoc_insertion_point(class_scope:ErrorModel)
    },
)
_sym_db.RegisterMessage(ErrorModel)

DiscreteErrorParams = _reflection.GeneratedProtocolMessageType(
    "DiscreteErrorParams",
    (_message.Message,),
    {
        "DESCRIPTOR": _DISCRETEERRORPARAMS,
        "__module__": "error_pb2"
        # @@protoc_insertion_point(class_scope:DiscreteErrorParams)
    },
)
_sym_db.RegisterMessage(DiscreteErrorParams)

ContinuousErrorParams = _reflection.GeneratedProtocolMessageType(
    "ContinuousErrorParams",
    (_message.Message,),
    {
        "DESCRIPTOR": _CONTINUOUSERRORPARAMS,
        "__module__": "error_pb2"
        # @@protoc_insertion_point(class_scope:ContinuousErrorParams)
    },
)
_sym_db.RegisterMessage(ContinuousErrorParams)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
