# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: param_string.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="param_string.proto",
    package="",
    syntax="proto3",
    serialized_options=b"\252\002\010Protobuf",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x12param_string.proto"A\n\nInputValue\x12\x11\n\x07numeric\x18\x01 \x01(\x01H\x00\x12\x0e\n\x04\x65xpr\x18\x02 \x01(\tH\x00\x42\x10\n\x0erepresentation"U\n\x0bInputValue3\x12\x16\n\x01x\x18\x01 \x01(\x0b\x32\x0b.InputValue\x12\x16\n\x01y\x18\x02 \x01(\x0b\x32\x0b.InputValue\x12\x16\n\x01z\x18\x03 \x01(\x0b\x32\x0b.InputValue"@\n\x0bGlobalParam\x12\x15\n\rvariable_name\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.InputValueB\x0b\xaa\x02\x08Protobufb\x06proto3',
)


_INPUTVALUE = _descriptor.Descriptor(
    name="InputValue",
    full_name="InputValue",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="numeric",
            full_name="InputValue.numeric",
            index=0,
            number=1,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="expr",
            full_name="InputValue.expr",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="representation",
            full_name="InputValue.representation",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=22,
    serialized_end=87,
)


_INPUTVALUE3 = _descriptor.Descriptor(
    name="InputValue3",
    full_name="InputValue3",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="x",
            full_name="InputValue3.x",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="y",
            full_name="InputValue3.y",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="z",
            full_name="InputValue3.z",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=89,
    serialized_end=174,
)


_GLOBALPARAM = _descriptor.Descriptor(
    name="GlobalParam",
    full_name="GlobalParam",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="variable_name",
            full_name="GlobalParam.variable_name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="GlobalParam.value",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=176,
    serialized_end=240,
)

_INPUTVALUE.oneofs_by_name["representation"].fields.append(
    _INPUTVALUE.fields_by_name["numeric"]
)
_INPUTVALUE.fields_by_name["numeric"].containing_oneof = _INPUTVALUE.oneofs_by_name[
    "representation"
]
_INPUTVALUE.oneofs_by_name["representation"].fields.append(
    _INPUTVALUE.fields_by_name["expr"]
)
_INPUTVALUE.fields_by_name["expr"].containing_oneof = _INPUTVALUE.oneofs_by_name[
    "representation"
]
_INPUTVALUE3.fields_by_name["x"].message_type = _INPUTVALUE
_INPUTVALUE3.fields_by_name["y"].message_type = _INPUTVALUE
_INPUTVALUE3.fields_by_name["z"].message_type = _INPUTVALUE
_GLOBALPARAM.fields_by_name["value"].message_type = _INPUTVALUE
DESCRIPTOR.message_types_by_name["InputValue"] = _INPUTVALUE
DESCRIPTOR.message_types_by_name["InputValue3"] = _INPUTVALUE3
DESCRIPTOR.message_types_by_name["GlobalParam"] = _GLOBALPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputValue = _reflection.GeneratedProtocolMessageType(
    "InputValue",
    (_message.Message,),
    {
        "DESCRIPTOR": _INPUTVALUE,
        "__module__": "param_string_pb2"
        # @@protoc_insertion_point(class_scope:InputValue)
    },
)
_sym_db.RegisterMessage(InputValue)

InputValue3 = _reflection.GeneratedProtocolMessageType(
    "InputValue3",
    (_message.Message,),
    {
        "DESCRIPTOR": _INPUTVALUE3,
        "__module__": "param_string_pb2"
        # @@protoc_insertion_point(class_scope:InputValue3)
    },
)
_sym_db.RegisterMessage(InputValue3)

GlobalParam = _reflection.GeneratedProtocolMessageType(
    "GlobalParam",
    (_message.Message,),
    {
        "DESCRIPTOR": _GLOBALPARAM,
        "__module__": "param_string_pb2"
        # @@protoc_insertion_point(class_scope:GlobalParam)
    },
)
_sym_db.RegisterMessage(GlobalParam)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
